
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: sales-api
        resources:
          requests:
            cpu: "500m" # I need access to 1/2 core on the node.
          limits:
            cpu: "500m" # Execute instructions 50ms/100ms on my 1 core.
